CREATE TABLE base_device_model (
  id                      BIGINT          NOT NULL      AUTO_INCREMENT COMMENT '编号',
  name                    VARCHAR(100)    NOT NULL      COMMENT '设备型号名称',
  device_type             CHAR(1)         NOT NULL      COMMENT '设备类型（0 边缘计算盒子 1 服务器）',
  memory                  INT             NOT NULL      COMMENT '内存(GB)',
  disk                    INT             DEFAULT NULL  COMMENT '硬盘容量(GB)',
  os                      CHAR(1)         DEFAULT NULL  COMMENT '操作系统（0 Linux 1 Windows 2 其他）',
  motherboard_manufacturer VARCHAR(100)   DEFAULT NULL  COMMENT '主板厂家',
  cpu_model               VARCHAR(50)     DEFAULT NULL  COMMENT 'CPU型号',
  cpu_cores               INT             DEFAULT NULL  COMMENT 'CPU核心数',
  cpu_frequency           DECIMAL(10,2)   DEFAULT NULL  COMMENT '主频(GHz)',
  cpu_count               INT             DEFAULT NULL  COMMENT 'CPU数量',
  gpu_model               VARCHAR(100)    DEFAULT NULL  COMMENT 'GPU型号',
  gpu_compute_power       VARCHAR(50)     DEFAULT NULL  COMMENT 'GPU算力',
  gpu_memory              INT             DEFAULT NULL  COMMENT '显存(GB)',
  gpu_count               INT             DEFAULT NULL  COMMENT 'GPU数量',
  status                  CHAR(1)         NOT NULL      DEFAULT '0' COMMENT '状态（0 正常 1 停用）',
  create_time             DATETIME        DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_time             DATETIME        DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  create_by               VARCHAR(64)     DEFAULT ''    COMMENT '创建人',
  update_by               VARCHAR(64)     DEFAULT ''    COMMENT '更新人',
  remark                  VARCHAR(500)    DEFAULT ''    COMMENT '备注',
  del_flag                CHAR(1)         DEFAULT '0'   COMMENT '删除标志（0 正常 1 删除）',
  PRIMARY KEY (id),
  KEY idx_name (name) COMMENT '设备型号名称索引',
  KEY idx_device_type (device_type) COMMENT '设备类型索引'
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COMMENT='设备型号管理表';
